DROP TABLE IF EXISTS ARTIST;
 
CREATE TABLE ARTIST (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ARTIST_FULL_NAME VARCHAR(250) NOT NULL,
  ARTIST_ID_NUMBER VARCHAR(250) NOT NULL
);

INSERT INTO ARTIST (id, ARTIST_FULL_NAME, ARTIST_ID_NUMBER)
VALUES (1, 'ALEJANDRO RUEDA', '1037604310');

INSERT INTO ARTIST (id, ARTIST_FULL_NAME, ARTIST_ID_NUMBER)
VALUES (2, 'LAURA SALAZAR', '1037604311');